source 'https://github.com/saxiang/FSSpecs.git'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0'

target 'APIsKit_Example' do
  pod 'APIsKit', :path => '../'
#  pod 'cheungKit', :git => "https://github.com/saxiang/cheungKit.git"
  pod 'cheungKitTemp'
  target 'APIsKit_Tests' do
    inherit! :search_paths

    
  end
end
